---
- name: Stop MySQL service
  service:
    name: mysql
    state: stopped

- name: Ensure that MySQL service stopped
  shell: /etc/init.d/mysql stop

- name: Start MySQL daemon with --skip-grant-tables option for reseting password for root user
  shell: mysqld_safe --skip-grant-tables &

- name: Wait for MySQL daemon
  wait_for:
    port: "{{ mysql_port }}"
    delay: 5

- name: Reset password for root user
  shell: "mysql -uroot -e \"use mysql; update user set Password=PASSWORD('{{ mysql_root_password }}') where user='{{ mysql_root_username }}'; flush privileges;\""
