---
- hosts: localhost
  gather_facts: no

  vars_files:
    - ../config.yml
    - vars/ports.yml
    - vars/mysql.yml
    - vars/nginx.yml
    - vars/apache.yml

  vars:
    list:
      - ubuntu
      - cikit01
      - cikit02

  tasks:
    - debug: msg="{{ list | select('match', 'cikit') | list | count }}"
